BEGIN;

-- Shelter IDs are generated by the server so the creation audit can use the
-- same stable entity UUID in the same transaction.
GRANT INSERT(id) ON public.shelters TO geoalerta_runtime;

COMMIT;
